Repository canonical/jaas.ai, pull requests merged in 2019-04, with the labels that each got.

#79 Standardise entity headers on entity detail pages
  static/js/app/sticky-header.js
  static/sass/custom/_entities.scss
  static/sass/styles.scss
  templates/shared/_spicule_lead-gen-form.html
  templates/store/_entity-header.html
  templates/store/bundle-details.html
  templates/store/charm-details.html
  webapp/store/views.py
Labels: Review: Design +1, Review: QA +1

#88 Add search dropdown panel
  static/js/src/app.js
  static/js/src/modules/search-panel.js
  static/sass/custom/_search-panel.scss
  static/sass/styles.scss
  templates/_layout.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#93 Add the python test job to Circle CI
  .circleci/config.yml
Labels: Review: Code +1

#97 Fix homepage
  tests/jaasai/__init__.py
  tests/jaasai/test_views.py
  tests/store/test_views.py
  webapp/store/views.py
Labels: Review: Code needed, Review: QA needed

#95 Restore user urls
  package.json
  tests/store/test_views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#96 Normalise model properties for templates
  templates/store/_entity-header.html
  templates/store/bundle-details.html
  templates/store/charm-details.html
  tests/store/test_models.py
  webapp/store/models.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#119 Fix ProxyFix DeprecationWarning.
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#121 Remove the charmers page
  templates/jaasai/community.html
  templates/jaasai/community/charmers.html
  tests/jaasai/test_views.py
  webapp/jaasai/views.py
Labels: Review: Code +1, Review: QA +1

#120 Update /kubernetes content.
  templates/jaasai/kubernetes.html
Labels: Review: Code +1, Review: QA +1

#122 Generate the static URLS in the view tests
  tests/jaasai/test_views.py
  tests/store/test_views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#123 Add blog redirect
  tests/redirects/test_views.py
  tests/store/test_views.py
  webapp/app.py
  webapp/redirects/views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#124 Update relate command
  static/js/cli-typer.js
Labels: Review: Code +1, Review: QA +1

#126 Add/update browser titles
  templates/404.html
  templates/_layout.html
  templates/jaasai/index.html
Labels: Review: Code +1, Review: QA +1

#128 Add 500 error page
  templates/500.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#135 Update /experts content
  templates/jaasai/experts.html
Labels: Review: Code +1, Review: QA +1

#134 Update community content
  templates/jaasai/community.html
Labels: Review: Code +1, Review: QA +1

#125 Update the CDK name
  templates/jaasai/containers.html
  templates/jaasai/jaas.html
  templates/jaasai/kubernetes.html
  tests/store/test_models.py
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1

#132 Update /openstack content
  static/img/topics/openstack-landscape-autopilot.png
  templates/jaasai/openstack.html
Labels: Review: Code +1, Review: QA +1

#133 Fix /community/cards page
  templates/jaasai/community/cards.html
Labels: Review: Code +1, Review: QA +1

#131 Render Markdown descriptions
  templates/store/bundle-details.html
  tests/store/test_models.py
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1

#136 Update Azure logo
  static/img/home/deploy-logos-2x.png
  static/img/home/deploy-logos.png
Labels: Review: Code +1, Review: QA +1

#146 Fix profile loading
  scripts/update_test_json.py
  tests/store/json/user-entities.json
  tests/store/test_views.py
  tests/store/testdata.py
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1

#139 Update the Spicule about section
  templates/jaasai/experts/spicule.html
Labels: Review: Code +1, Review: QA +1

#144 Update Spicule logo on the Spicule page
  templates/jaasai/experts/spicule.html
Labels: Review: Code +1, Review: QA +1

#138 Update Spicule cards
  templates/jaasai/index.html
  templates/shared/_spicule-card.html
  templates/store/store.html
Labels: Review: Code +1, Review: QA +1

#143 Update Spicule bundles
  static/sass/styles.scss
  templates/jaasai/experts/spicule.html
Labels: Review: Code +1, Review: QA +1

#145 Update Tengu bundle links
  templates/jaasai/experts/tengu.html
Labels: Review: Code +1, Review: QA +1

#149 Add support page
  templates/jaasai/support.html
  tests/jaasai/test_views.py
  webapp/jaasai/views.py
Labels: Review: Code +1, Review: QA +1

#151 Add Tengu cards
  templates/jaasai/index.html
  templates/shared/_spicule-card.html
  templates/shared/store-card/_card.html
  templates/shared/store-card/_random.html
  templates/shared/store-card/_spicule.html
  templates/shared/store-card/_tengu.html
  templates/store/store.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#150 Update big-data page
  templates/jaasai/big-data.html
Labels: Review: Code +1, Review: QA +1

#147 Refactor nav to improve responsiveness and tidy up layout bugs
  static/sass/custom/_header.scss
  static/sass/custom/_search-panel.scss
  static/sass/styles.scss
  templates/_layout.html
  templates/shared/_navigation-search.html
  templates/shared/header.html
  templates/shared/navigation.html
  templates/shared/search-panel.html
  webapp/app.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#155 Selected nav items should be highlighted
  static/sass/custom/_header.scss
  templates/jaasai/jaas.html
  templates/shared/navigation.html
  templates/store/bundle-details.html
  templates/store/charm-details.html
  templates/store/search.html
  templates/store/store.html
Labels: Review: Code +1, Review: QA +1

#154 Remove hardcoded tags
  static/sass/custom/_search-panel.scss
  templates/shared/search-panel.html
Labels: Review: Code +1, Review: QA +1

#160 Use ‘q’ instead of ‘name’ as search query identifier
  templates/shared/_navigation-search.html
Labels: Review: Code +1, Review: QA +1

#161 Remove hard coded store tag counts
  templates/store/store.html
Labels: Review: Code +1, Review: QA +1

#162 Use Vanilla search box pattern
  static/sass/custom/_header.scss
  static/sass/custom/_search-panel.scss
  templates/shared/_navigation-search.html
Labels: Review: Code +1, Review: QA +1

#163 Update ‘Getting started’ link in primary nav
  webapp/app.py
Labels: Review: Code needed, Review: QA needed

#158 Add terms
  templates/store/charm-details.html
  tests/store/test_models.py
  tests/store/test_views.py
  webapp/store/models.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#156 Add blog feed
  .eslintrc.js
  .gitignore
  package.json
  requirements.txt
  static/js/src/blog-feed.js
  templates/_layout.html
  templates/jaasai/community.html
  templates/shared/navigation.html
  tests/jaasai/test_views.py
  webapp/app.py
  webapp/external_urls.py
  webapp/jaasai/views.py
  webapp/redirects/views.py
  webpack.config.js
Labels: Review: Code +1, Review: QA +1

#167 Add entity expert cards
  static/sass/styles.scss
  templates/jaasai/experts.html
  templates/jaasai/experts/spicule.html
  templates/jaasai/experts/tengu.html
  templates/shared/_spicule_lead-gen-form.html
  templates/shared/contact-card/_card.html
  templates/shared/contact-card/_entity-page.html
  templates/shared/contact-card/_expert-page.html
  templates/shared/store-card/_card.html
  templates/shared/store-card/_random.html
  templates/shared/store-card/_spicule.html
  templates/shared/store-card/_tengu.html
  templates/store/bundle-details.html
  templates/store/charm-details.html
  webapp/experts.py
  webapp/jaasai/views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#173 Add static hashing
  templates/_layout.html
  templates/jaasai/big-data.html
  templates/jaasai/community.html
  templates/jaasai/community/partners.html
  templates/jaasai/containers.html
  templates/jaasai/how-it-works.html
  templates/jaasai/index.html
  templates/jaasai/jaas.html
  templates/jaasai/kubernetes.html
  templates/jaasai/openstack.html
  templates/jaasai/support.html
  templates/store/bundle-details.html
  templates/store/charm-details.html
  templates/store/store.html
  webapp/app.py
  webapp/experts.py
  webapp/template_utils.py
Labels: Project Fuse ⚡️, Review: Code +1, Review: QA +1

#174 Implement the wider grid in Vanilla
  static/js/src/app.js
  static/sass/custom/_header.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: Design needed, Review: QA +1

#178 Update header items
  templates/jaasai/how-it-works.html
  templates/shared/navigation.html
Labels: Review: QA +1

#177 Fix revision info
  templates/store/_entity-header.html
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1

#175 Add supported cards
  templates/shared/_plan-card.html
  templates/store/bundle-details.html
  templates/store/charm-details.html
  tests/store/test_models.py
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1

#176 Add robots and sitemaps
  static/robots.txt
  templates/sitemaps/sitemap-base.xml
  templates/sitemaps/sitemap-store.xml
  templates/sitemaps/sitemap.xml
  webapp/jaasai/views.py
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1

#184 Update issues URL
  webapp/external_urls.py
Labels: Review: Code needed, Review: QA needed

#182 Fix primary nav responsive bug
  static/sass/custom/_header.scss
  templates/shared/navigation.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#191 Add ‘juju deploy’ to copy snippet in entity header
  templates/store/_entity-header.html
Labels: Review: Code +1, Review: QA +1

#181 Refactor styling of search results
  static/sass/custom/_entities.scss
  static/sass/custom/_search-results.scss
  static/sass/custom/_series_tags.scss
  static/sass/styles.scss
  templates/store/_entity-header.html
  templates/store/_search_row.html
  templates/store/search.html
  templates/store/user-details.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#194 Tweak headings across the site
  static/sass/styles.scss
  templates/jaasai/how-it-works.html
  templates/jaasai/index.html
  templates/jaasai/jaas.html
  templates/store/store.html
Labels: Review: Code +1, Review: Design +1

#199 Add spacing to “Why use Juju” on index
  templates/jaasai/index.html
Labels: Review: Code +1, Review: Design +1

#183 Update home background and fix mobile
  static/sass/custom/_homepage-hero-promo.scss
  templates/jaasai/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#179 Improve search quality
  tests/store/test_views.py
  webapp/store/models.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#204 Improve entity filter URLs
  templates/store/search.html
  tests/store/test_views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#203 Fix search strings
  templates/shared/search-panel.html
  templates/store/store.html
Labels: Review: Code +1, Review: QA +1

#202 Use the CachedSession from canonicalwebteam.http
  .gitignore
  requirements.txt
  tests/jaasai/test_views.py
  webapp/jaasai/views.py
Labels: Project Fuse ⚡️, Review: Code +1, Review: QA +1

#205 Update margins on homepage promos
  templates/jaasai/index.html
Labels: Review: Design +1

#196 Refactor nav to use Vanilla navigation pattern
  static/js/src/modules/search-panel.js
  static/sass/custom/_header.scss
  static/sass/custom/_search-panel.scss
  templates/shared/_navigation-search.html
  templates/shared/header.html
  templates/shared/navigation.html
Labels: Review: Design +1, Review: QA +1

#207 Add bottom margin to series tags in entity header
  static/sass/custom/_search-results.scss
  templates/store/_entity-header.html
Labels: Review: Code +1, Review: QA +1

#209 Fix broken charm icons in search results
  templates/store/_search_row.html
  templates/store/bundle-details.html
Labels: Review: Code +1, Review: QA +1
