Repository canonical/jaas.ai, pull requests merged in 2019-03, with the labels that each got.

#37 Preconnect to Assets Server and Google Analytics
  templates/_layout.html
Labels: Project Fuse ⚡️

#31 Update site navigation
  package.json
  static/js/app.js
  static/js/src/app.js
  static/sass/styles.scss
  templates/_layout.html
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#42 Ignore built JS asset
  .gitignore
  package.json
  static/js/app.js
  templates/_layout.html
Labels: Review: Code +1

#45 Point to new @canonical/global-nav
  package.json
  static/js/src/app.js
  yarn.lock
Labels: Review: Code +1

#47 Remove Google+
  templates/_layout.html
  templates/jaasai/community.html
  templates/store/bundle-details.html
  templates/store/charm-details.html
Labels: Review: Code +1

#50 Updated resolutions values in package.json to upgrade sub dependenciess lodash, braces, and minimatch that have vulnerabilities.
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#52 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Review: Code +1

#48 Bundle copy-snippet as ES6 module
  static/js/src/app.js
  static/js/src/modules/copy-snippet.js
Labels: Review: Code +1, Review: QA +1

#62 Remove OIL program from the site
  templates/jaasai/community.html
  templates/jaasai/community/partners.html
  templates/jaasai/openstack.html
Labels: Review: Code +1, Review: Design needed, Review: QA +1

#71 Add /getting-started page
  templates/_layout.html
  webapp/jaasai/views.py
Labels: Review: Code +1, Review: QA +1

#72 Increase the nav breakpoint
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#69 Don't show the login in the global nav
  static/js/src/app.js
Labels: Review: Code +1, Review: QA +1

#67 Add basic view tests
  package.json
  requirements.txt
  tests/__init__.py
  tests/store/__init__.py
  tests/store/test_views.py
Labels: Review: Code +1

#70 Set Spicule logo size on the homepage
  templates/jaasai/index.html
Labels: Review: Code +1, Review: QA +1

#60 Add basic search
  static/sass/custom/_search-box.scss
  static/sass/styles.scss
  templates/_layout.html
  templates/store/search.html
  webapp/store/models.py
  webapp/store/views.py
Labels: Review: Code needed, Review: QA needed

#75 Add community results
  package.json
  templates/store/search.html
  tests/store/test_models.py
  tests/store/test_views.py
  tests/store/testdata.py
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1

#74 Improve search performance
  webapp/store/models.py
Labels: Project Fuse ⚡️, Review: Code +1, Review: QA +1

#77 Show message when there are no results
  templates/store/search.html
  tests/store/test_views.py
  webapp/store/views.py
Labels: Review: Code needed, Review: QA needed

#78 Redirect searches
  tests/store/test_views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#76 Add sorting and filtering
  static/sass/custom/_search-results.scss
  templates/store/charm-details.html
  templates/store/search.html
  tests/store/test_models.py
  webapp/store/models.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#81 Show search count
  templates/store/search.html
Labels: Review: QA +1

#25 Lead generation modal for Spicule
  .circleci/config.yml
  .env
  package.json
  static/js/app/modal.js
  static/sass/custom/_modal.scss
  static/sass/styles.scss
  templates/jaasai/experts/spicule.html
  templates/jaasai/experts/thanks.html
  templates/shared/_spicule_lead-gen-form.html
  templates/store/bundle-details.html
  webapp/jaasai/views.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1
