Repository canonical/jaas.ai, pull requests merged in 2019-08, with the labels that each got.

#406 GitHub not Github
  templates/jaasai/index.html
Labels: Review: Code +1, Review: QA +1

#395 Add linkable headings to docs
  static/sass/custom/_linkable-heading.scss
  static/sass/styles.scss
  templates/docs/document.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#409 Amend K8s entity header message link
  templates/store/_entity-header.html
Labels: Review: Code needed

#411 increase charmstore timeout
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1

#412 Swap out gfm for py-gfm to support backticks
  requirements.txt
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1

#404 Add /case-studies blog setup
  .gitignore
  requirements.txt
  static/sass/custom/_case_studies.scss
  static/sass/styles.scss
  templates/blog/_case-study-card.html
  templates/blog/_newsletter-signup-form.html
  templates/blog/_newsletter-success.html
  templates/blog/_pagination.html
  templates/blog/archives.html
  templates/blog/article.html
  templates/blog/index.html
  webapp/app.py
Labels: Review: Code +1, Review: Design +1, Review: QA needed
