Repository canonical/jaas.ai, pull requests merged in 2019-09, with the labels that each got.

#421 Redirect logo
  permanent-redirects.yaml
  tests/redirects/test_views.py
Labels: Review: Code +1, Review: QA +1

#417 Add Omnivector /experts page
  templates/jaasai/experts/omnivector.html
  webapp/experts.py
  webapp/jaasai/views.py
Labels: Review: Code +1, Review: QA +1

#414 Use image_template module on homepage
  .circleci/config.yml
  requirements.txt
  static/sass/styles.scss
  templates/_layout.html
  templates/jaasai/index.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#424 Add /case-studies
  .gitignore
  requirements.txt
  static/sass/custom/_case_studies.scss
  static/sass/styles.scss
  templates/blog/_case-study-card.html
  templates/blog/_newsletter-signup-form.html
  templates/blog/_newsletter-success.html
  templates/blog/_pagination.html
  templates/blog/archives.html
  templates/blog/article.html
  templates/blog/index.html
  webapp/app.py
Labels: Review: Code needed, Review: QA +1

#352 Add slider content to the homepage hero section
  static/js/tabpanel.js
  static/sass/custom/_patterns_hero-tab.scss
  static/sass/styles.scss
  templates/jaasai/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#429 Switch out sass-lint for stylelint ✨
  .circleci/config.yml
  .sass-lint.yml
  .stylelintrc
  package.json
  static/sass/custom/_hljs.scss
  static/sass/styles.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#425 Add Omnivector & Tengu contact forms
  templates/jaasai/experts/omnivector.html
  templates/jaasai/experts/spicule.html
  templates/jaasai/experts/tengu.html
  templates/shared/_expert_partner_cta_strip.html
  templates/shared/_omnivector_lead-gen-form.html
  templates/shared/_tengu_lead-gen-form.html
  templates/shared/contact-card/_card.html
  templates/shared/store-card/_random.html
  webapp/jaasai/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#431 Update test script to use scss-lint script
  package.json
Labels: Review: Code +1, Review: QA +1

#434 Make the titles dynamic in the documentation
  templates/docs/base.html
Labels: Review: Code +1, Review: QA +1

#446 Update Juju Twitter account
  templates/_layout.html
Labels: Review: Code +1

#445 Add image module to /how-it-works
  requirements.txt
  templates/jaasai/how-it-works.html
Labels: Review: Code +1, Review: QA +1
