Repository canonical/jaas.ai, pull requests merged in 2019-10, with the labels that each got.

#444 Add image module to /store
  static/sass/styles.scss
  templates/shared/store-card/_card.html
  templates/store/store.html
Labels: Review: Code +1

#451 Prevent initial hero image from lazy loading
  templates/jaasai/index.html
Labels: Review: Code +1, Review: QA +1

#460 Audit site head to improve page render time
  templates/_layout.html
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#463 Track requests log
  requirements.txt
  webapp/app.py
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1

#461 Upgrade image template to v1.0.0
  requirements.txt
  templates/_layout.html
  templates/jaasai/how-it-works.html
  templates/jaasai/index.html
  templates/shared/search-panel.html
  templates/shared/store-card/_card.html
  templates/store/store.html
Labels: Review: Code +1, Review: QA +1

#462 Tweak JAAS logo on homepage
  templates/jaasai/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#464 Update Python testing infrastructure
  .circleci/config.yml
  package.json
  run
Labels: Review: Code +1, Review: QA +1

#466 Reduce docker image size
  .dockerignore
  Dockerfile
Labels: Review: Code +1, Review: QA +1
