Repository canonical/jaas.ai, pull requests merged in 2019-07, with the labels that each got.

#342 Update juju-cards to v1.7.2
  templates/jaasai/big-data.html
  templates/jaasai/community/cards.html
  templates/jaasai/openstack.html
  templates/store/bundle-details.html
  templates/store/charm-details.html
Labels: Review: Code +1, Review: QA +1

#343 Update the store hero section
  static/sass/custom/_homepage-hero-promo.scss
  static/sass/custom/_store-promos.scss
  static/sass/styles.scss
  templates/shared/store-card/_card.html
  templates/store/store.html
  webapp/experts.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#345 Update the store page content
  static/sass/styles.scss
  templates/store/store.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#348 Update the deploy image on the how it works page
  templates/jaasai/how-it-works.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#346 Update the about content design
  static/sass/custom/_patterns_strips.scss
  static/sass/styles.scss
  templates/jaasai/jaas.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#351 Update the how it works page design
  templates/jaasai/how-it-works.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#350 Update details header design
  static/sass/custom/_patterns_strips.scss
  templates/store/_entity-header.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#353 Add dynamic year variable to footer
  templates/_layout.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#354 Update the why use juju images
  templates/jaasai/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#355 Updated badges
  README.md
Labels: Review: Code +1, Review: QA +1

#358 Fix spacing on /experts strap
  templates/jaasai/experts/spicule.html
  templates/jaasai/experts/tengu.html
Labels: Review: Code +1, Review: QA +1

#357 Update copy
  templates/jaasai/kubernetes.html
Labels: Review: Code +1, Review: QA +1

#359 Update copy on index hero
  templates/jaasai/index.html
Labels: Review: Code +1, Review: QA +1

#364 Tengu copy updates
  templates/jaasai/experts/tengu.html
  webapp/experts.py
Labels: Review: Code +1, Review: QA +1

#363 Add docs module
  requirements.txt
  templates/docs/_notification.html
  templates/docs/base.html
  templates/docs/commands.html
  templates/docs/document.html
  templates/docs/homepage.html
  webapp/app.py
  webapp/docs/views.py
Labels: Review: Code needed, Review: QA needed

#365 Fix broken link on /how-it-works
  templates/jaasai/how-it-works.html
Labels: Review: Code +1, Review: QA +1

#368 Fix rendering of charms without readmes
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1

#371 Add the template for docs
  static/js/highlight.pack.js
  static/sass/custom/_hljs.scss
  static/sass/custom/_patterns_docs.scss
  static/sass/styles.scss
  templates/docs/base.html
  templates/docs/commands.html
  templates/docs/document.html
  templates/docs/homepage.html
  templates/shared/header.html
Labels: Review: Code +1, Review: QA +1

#366 Add linkchecker checks
  .circleci/config.yml
Labels: Review: QA +1

#382 Fix Charmstore timeouts
  templates/store/_entity-header.html
  tests/store/test_models.py
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1

#383 Add search module for documentation
  .circleci/config.yml
  requirements.txt
  templates/docs/search.html
  webapp/docs/views.py
Labels: Review: Code +1, Review: QA +1

#384 Add the docs search templates
  templates/docs/base.html
  templates/docs/homepage.html
  templates/docs/search.html
Labels: Review: Code +1, Review: QA +1

#390 Fix broken docs homepage links
  templates/docs/homepage.html
Labels: Review: Code needed, Review: QA needed

#379 Upgrade site to Vanilla Framework v2.1.0
  package.json
  static/sass/custom/_patterns_docs.scss
  static/sass/custom/_patterns_strips.scss
  static/sass/custom/_search-panel.scss
  static/sass/styles.scss
  templates/jaasai/experts.html
  templates/jaasai/experts/spicule.html
  templates/jaasai/experts/tengu.html
  templates/jaasai/how-it-works.html
  templates/jaasai/index.html
  templates/jaasai/jaas.html
  templates/jaasai/kubernetes.html
  templates/jaasai/openstack.html
  templates/shared/store-card/_card.html
  templates/store/store.html
  webapp/experts.py
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#392 Add redirect for /support/create to /support
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#396 Sitemap and change search to jaas.ai/docs
  requirements.txt
  webapp/docs/views.py
Labels: Review: Code +1, Review: QA +1

#393 Update links site wide to reflect new docs structure
  templates/404.html
  templates/_layout.html
  templates/jaasai/how-it-works.html
  templates/jaasai/jaas.html
  templates/jaasai/support.html
  templates/store/search.html
  templates/store/store.html
  webapp/external_urls.py
Labels: Review: Code +1, Review: QA +1

#380 Disable add-to-canvas button on kubernetes charms.
  templates/store/_entity-header.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#401 Fix “Copy to clipboard” function in entity header
  static/js/src/modules/copy-snippet.js
Labels: Review: Code +1, Review: QA +1

#394 Switch out 'Ask Ubuntu' links for Discourse links
  templates/jaasai/community.html
  templates/jaasai/index.html
  webapp/external_urls.py
Labels: Review: Code +1, Review: QA +1

#397 Remove homepage to use discourse topic
  templates/docs/homepage.html
  webapp/docs/views.py
Labels: Review: Code +1, Review: QA +1

#403 Upgrade dependencies.
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1
