Repository canonical/jaas.ai, pull requests merged in 2019-05, with the labels that each got.

#212 Search icon cleanup
  static/img/icons/default-bundle.png
  static/img/icons/default-bundle.svg
  static/img/icons/default-charm.png
  static/img/icons/default-charm.svg
  templates/store/_search_row.html
  templates/store/bundle-details.html
  templates/store/search.html
  templates/store/user-details.html
Labels: Review: Code +1, Review: QA +1

#216 Resize and restyle 'What people saying' section on homepage
  static/img/logos/epam.svg
  templates/jaasai/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#224 Update active nav color
  static/sass/styles.scss
Labels: Review: Design +1

#233 Fix home hero card spacing
  templates/jaasai/index.html
Labels: Review: Code +1, Review: QA +1

#231 Fix search filters
  tests/store/test_views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#238 How It Works alignment
  templates/jaasai/how-it-works.html
Labels: Review: Code +1, Review: QA +1

#239 Fix series wrapping on search results
  static/sass/custom/_search-results.scss
Labels: Review: Code +1, Review: QA +1

#234 Collapse to two columns on homepage
  static/sass/styles.scss
  templates/jaasai/index.html
Labels: Review: Code +1, Review: QA +1

#230 Fix revision URLs
  scripts/update_test_json.py
  tests/store/json/bundle.json
  tests/store/json/charm.json
  tests/store/json/search.json
  tests/store/test_models.py
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1

#222 Display a series dropdown
  static/js/src/search-filters.js
  static/sass/custom/_search-results.scss
  static/sass/custom/_series_tags.scss
  templates/store/_search_row.html
  templates/store/search.html
  tests/store/test_views.py
  webapp/app.py
  webapp/store/views.py
  webapp/template_utils.py
  webpack.config.js
Labels: Review: Code +1, Review: QA +1

#241 Update the Container strip on the store.
  templates/store/store.html
Labels: Review: Code needed, Review: QA needed

#240 Home bundle name wrapping
  static/sass/styles.scss
  templates/jaasai/index.html
Labels: Review: Code needed, Review: QA needed

#226 Tidy up featured promos in /store
  static/sass/styles.scss
  templates/store/store.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#246 Align search rows to the top
  static/sass/custom/_entities.scss
  static/sass/custom/_search-results.scss
  templates/store/_entity-header.html
  templates/store/_search_row.html
Labels: Review: Code needed, Review: QA needed

#245 High res build it yourself image
  templates/jaasai/index.html
Labels: Review: Code needed, Review: QA needed

#243 Add cookie-policy
  package.json
  static/js/src/app.js
  static/sass/styles.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#259 Series labels colours
  static/sass/custom/_series_tags.scss
Labels: Review: Code needed, Review: QA needed

#260 Fix paragraph spacing
  static/sass/styles.scss
Labels: Review: Code needed, Review: QA needed

#258 Remove squircles
  static/sass/custom/_entities.scss
  static/sass/custom/_search-panel.scss
  templates/shared/search-panel.html
  templates/store/bundle-details.html
Labels: Review: Code needed, Review: QA needed

#262 Add Usabilla for user feedback
  templates/_layout.html
Labels: Review: QA needed

#261 Accessibility improvements
  templates/_layout.html
  templates/jaasai/big-data.html
  templates/jaasai/community/partners.html
  templates/jaasai/containers.html
  templates/jaasai/experts.html
  templates/jaasai/experts/spicule.html
  templates/jaasai/experts/tengu.html
  templates/jaasai/how-it-works.html
  templates/jaasai/index.html
  templates/jaasai/jaas.html
  templates/jaasai/kubernetes.html
  templates/jaasai/openstack.html
  templates/jaasai/support.html
  templates/shared/header.html
  templates/shared/search-panel.html
Labels: Review: Code +1, Review: QA +1

#263 Remove rogue underline from charm icons
  static/sass/styles.scss
  templates/_layout.html
  templates/store/_search_row.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#264 bug_url to bugs_url
  templates/store/charm-details.html
Labels: Review: Code +1

#266 Perf improvements
  package.json
  templates/_layout.html
Labels: Project Fuse ⚡️, Review: Code +1, Review: QA +1

#268 ./run v3.4.0, talisker fixes, remove dependencies
  .gitignore
  entrypoint
  requirements.txt
  run
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#257 Add bundle icons
  static/js/src/search-icons.js
  static/sass/custom/_search-results.scss
  templates/store/_search_row.html
  templates/store/search.html
  templates/store/user-details.html
  tests/store/test_models.py
  webapp/store/models.py
  webpack.config.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#270 Bump global nav to 2.0.8
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#274 Fix /search?requires= error
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1

#277 Search queries should be more than two characters
  templates/store/search.html
Labels: Review: Code +1, Review: QA +1

#281 Fix robots.txt file and serve sitemap filetypes as xml
  static/robots.txt
  webapp/jaasai/views.py
Labels: Review: Code +1, Review: QA +1

#296 Move Your models link
  static/sass/custom/_header.scss
  templates/shared/header.html
Labels: Review: QA +1

#287 Use default charmstore
  templates/store/bundle-details.html
  tests/store/test_models.py
  webapp/store/models.py
  yarn.lock
Labels: Review: QA +1

#298 Update username formatting on the profile
  templates/store/user-details.html
Labels: Review: QA +1

#299 Add tests for fetching requires/provides
  tests/store/test_models.py
  webapp/store/models.py
Labels: Review: QA +1

#300 Update container image width
  templates/store/store.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#297 Add windows series filter
  templates/store/search.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#309 Fix clipboard icon cutting off the end of the CLI deploy command
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1
