Repository canonical/jaas.ai, pull requests merged in 2019-06, with the labels that each got.

#311 Fix build and correct postcss command
  .circleci/config.yml
  package.json
Labels: Review: Code +1, Review: QA +1

#317 Update social icons
  templates/_layout.html
Labels: Review: Code needed, Review: QA needed

#318 Fix video link spacing.
  static/sass/custom/_homepage-hero-promo.scss
  templates/jaasai/index.html
Labels: Review: QA +1

#319 Update GUI links
  templates/jaasai/how-it-works.html
  templates/jaasai/jaas.html
Labels: Review: Code +1, Review: QA +1

#335 Use flask base and remove useless code
  requirements.txt
  webapp/app.py
  webapp/extensions.py
  webapp/handlers.py
Labels: Review: Code +1, Review: QA +1

#337 Enhance the footer with a Suru pattern
  static/sass/custom/_patterns_icons.scss
  static/sass/custom/_patterns_lists.scss
  static/sass/custom/_patterns_strips.scss
  static/sass/styles.scss
  templates/_layout.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#338 Update the homepage hero with Suru
  static/sass/custom/_homepage-hero-promo.scss
  static/sass/custom/_patterns_strips.scss
  static/sass/styles.scss
  templates/_layout.html
  templates/jaasai/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#339 Add the is-slanted state to the strips pattern
  static/sass/custom/_patterns_strips.scss
  templates/_layout.html
  templates/jaasai/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#340 Update the homepage design
  static/sass/custom/_patterns_strips.scss
  static/sass/styles.scss
  templates/_layout.html
  templates/jaasai/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1
