Repository canonical/jaas.ai, pull requests merged in 2020-04, with the labels that each got.

#524 Update to focal
  .circleci/config.yml
  Dockerfile
  entrypoint
  requirements.txt
Labels: Review: Code needed, Review: QA needed

#525 Release banner
  templates/jaasai/index.html
  templates/shared/header.html
Labels: Review: Code +1, Review: QA +1

#526 Link to /models
  templates/jaasai/how-it-works.html
  templates/jaasai/index.html
  templates/jaasai/jaas.html
Labels: Review: Code +1, Review: QA +1

#529 Add secret key
  .circleci/config.yml
  .env
  Dockerfile
  entrypoint
  requirements.txt
Labels: Review: Code +1

#531 Move the period. Fixes: #530
  templates/jaasai/index.html
Labels: Review: Code +1, Review: QA +1

#532 Null check the access to toggle controller
  static/js/src/search-filters.js
Labels: Review: Code +1, Review: QA +1

#533 Update Prettier and add eslint linting
  .circleci/config.yml
  .eslintrc.js
  .prettierignore
  .stylelintrc
  package.json
  static/js/accordion.js
  static/js/cli-typer.js
  static/js/highlight.pack.js
  static/js/modules/global-nav/global-nav.js
  static/js/src/app.js
  static/js/src/blog-feed.js
  static/js/src/modules/copy-snippet.js
  static/js/src/modules/search-panel.js
  static/js/src/search-filters.js
  static/js/src/search-icons.js
  static/js/tabpanel.js
  static/js/treefilelist.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#534 Housekeeping and perf tweaks
  package.json
  static/sass/custom/_header.scss
  static/sass/custom/_linkable-heading.scss
  static/sass/custom/_modal.scss
  static/sass/custom/_patterns_icons.scss
  static/sass/styles.scss
  templates/_layout.html
  templates/jaasai/index.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#535 Fix social footer hover links
  templates/_layout.html
Labels: Review: Code +1, Review: QA +1

#536 Refactor modals JS to a module
  static/js/app/modal.js
  static/js/src/app.js
  static/js/src/modules/modal.js
  templates/shared/_omnivector_lead-gen-form.html
  templates/shared/_spicule_lead-gen-form.html
  templates/shared/_tengu_lead-gen-form.html
Labels: Performance ⚡️, Review: Code +1, Review: QA +1
