Repository canonical/jaas.ai, pull requests merged in 2020-07, with the labels that each got.

#560 Add domain jujulabs.ubuntu.com
  deploy/site.yaml
Labels: Review: Code +1

#565 Add Canonical URL to entity templates
  templates/_layout.html
  templates/store/bundle-details.html
  templates/store/charm-details.html
  tests/store/test_models.py
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1

#566 Rename deploy to konf
  konf/site.yaml
Labels: Review: QA +1

#568 Fix issue with markdown parser
  tests/store/test_models.py
  webapp/store/models.py
Labels: Review: Code +1, Review: QA +1
